//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimicsUpdation.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblrolemodulelink
    {
        public int MRMLID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public short IsVisible { get; set; }
        public short EnableAdd { get; set; }
        public short EnableEdit { get; set; }
        public short EnableDelete { get; set; }
        public short EnableReadOnly { get; set; }
        public short EnableReport { get; set; }
        public short IsSuperAdmin { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int IsDeleted { get; set; }
    
        public virtual unitworkccs_tblmodules unitworkccs_tblmodules { get; set; }
        public virtual unitworkccs_tblroles unitworkccs_tblroles { get; set; }
        public virtual unitworkccs_tblusers unitworkccs_tblusers { get; set; }
    }
}
