//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimicsUpdation.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tbloperatordetails
    {
        public int opId { get; set; }
        public string operatorName { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string machineIds { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public string modifiedBy { get; set; }
        public string operatorMobileNo { get; set; }
        public string operatorEmailId { get; set; }
        public string grade { get; set; }
        public string unit { get; set; }
        public string location { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> opNo { get; set; }
        public string contactNo { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string shift { get; set; }
        public Nullable<int> cellId { get; set; }
        public Nullable<int> subCellId { get; set; }
        public Nullable<int> plantId { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public string DirectOrIndirect { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfJoing { get; set; }
        public Nullable<int> PhotoId { get; set; }
    }
}
