//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimicsUpdation.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblissuedreceived
    {
        public int id { get; set; }
        public Nullable<int> shiftId { get; set; }
        public Nullable<int> opId { get; set; }
        public Nullable<int> machineId { get; set; }
        public Nullable<int> reasonId { get; set; }
        public string sapCode { get; set; }
        public string grnNo { get; set; }
        public string inspLotNo { get; set; }
        public string toolLifeActual { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<System.DateTime> issueDate { get; set; }
        public string sapReferenceNo { get; set; }
        public Nullable<System.DateTime> receiptDate { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<int> opAcceptanceFlag { get; set; }
        public Nullable<int> IsReturn { get; set; }
        public Nullable<int> toolGribUserId { get; set; }
        public Nullable<int> toolGribUserFlag { get; set; }
        public string uniqueBatchNo { get; set; }
        public string slipNo { get; set; }
        public string barCodeNo { get; set; }
        public Nullable<int> reasonLvl1Id { get; set; }
        public string toolBatchNo { get; set; }
        public Nullable<int> isReDisplay { get; set; }
        public string toolName { get; set; }
        public int returnedOpId { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> sapRefDate { get; set; }
        public string batchNumber { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<bool> isCheck { get; set; }
        public Nullable<int> isSAPGenerated { get; set; }
        public Nullable<System.DateTime> sapGeneratedDate { get; set; }
    }
}
