//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimicsUpdation.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblbreakdown_reportdetails
    {
        public int Id { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string CorrectedDate { get; set; }
        public Nullable<decimal> TotalTime { get; set; }
        public Nullable<decimal> OperatingTime { get; set; }
        public Nullable<decimal> DryRunTime { get; set; }
        public Nullable<decimal> SetUpTime { get; set; }
        public Nullable<decimal> LoadUnloadTime { get; set; }
        public Nullable<decimal> LossOrIdleTime { get; set; }
        public Nullable<decimal> BreakdownTime { get; set; }
        public Nullable<decimal> PowerOffOrDataLossTime { get; set; }
        public Nullable<decimal> Utilization { get; set; }
        public Nullable<decimal> ElectricalMaintenance { get; set; }
        public Nullable<decimal> MechanicalMaintenance { get; set; }
        public Nullable<decimal> Production { get; set; }
        public Nullable<decimal> HumanResource { get; set; }
        public Nullable<decimal> Quality { get; set; }
        public Nullable<decimal> ToolingStoppage { get; set; }
        public Nullable<decimal> Planning { get; set; }
        public Nullable<decimal> ElectricalMaintenance1 { get; set; }
        public Nullable<decimal> MechanicalMaintenance1 { get; set; }
        public Nullable<decimal> Production1 { get; set; }
        public Nullable<decimal> HumanResource1 { get; set; }
        public Nullable<decimal> Quality1 { get; set; }
        public Nullable<decimal> ToolingStoppage1 { get; set; }
        public Nullable<decimal> Planning1 { get; set; }
        public Nullable<System.DateTime> IsCreatedOn { get; set; }
        public Nullable<int> IsDeleted { get; set; }
    }
}
