//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimicsUpdation.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblcontrolplandetails
    {
        public int controlPlanDetId { get; set; }
        public string customerRefCpNo { get; set; }
        public string operationNo { get; set; }
        public string ballunNo { get; set; }
        public Nullable<int> processId { get; set; }
        public string specialCharacterClass { get; set; }
        public Nullable<int> dimension { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<decimal> minToleranace { get; set; }
        public Nullable<decimal> maxTolerance { get; set; }
        public string recordingMethod { get; set; }
        public string responsibility { get; set; }
        public string reactionPlan { get; set; }
        public string frequency { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public string evaluationMethod { get; set; }
        public Nullable<decimal> revisionNo { get; set; }
        public string operationalDescription { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public string partNo { get; set; }
        public Nullable<int> controlPlanId { get; set; }
    }
}
