//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimicsUpdation.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wimerasys_productwisedefectdetails
    {
        public int id { get; set; }
        public string trim { get; set; }
        public string plant { get; set; }
        public string partNumber { get; set; }
        public string partName { get; set; }
        public string defectCode { get; set; }
        public string defectDescription { get; set; }
    }
}
