//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimicsUpdation.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wimerasys_fgandcellallocationdetails
    {
        public int id { get; set; }
        public string plant { get; set; }
        public string materialDescription { get; set; }
        public string material { get; set; }
        public string cellFinal { get; set; }
        public string subCellFinal { get; set; }
        public string DMCOrQRCodeStatus { get; set; }
    }
}
