//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_facility_IdleHandlerWithOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_parameter_sensor_data_level
    {
        public int parameterSensorDataLevelId { get; set; }
        public Nullable<int> parameterSensorDataID { get; set; }
        public Nullable<decimal> levelValue { get; set; }
    }
}
