//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_facility_IdleHandlerWithOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblatccounter
    {
        public int ATCID { get; set; }
        public int MachineID { get; set; }
        public int ToolNo { get; set; }
        public int Counter { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public System.DateTime CycleStartTime { get; set; }
        public Nullable<System.DateTime> CycleEndTime { get; set; }
        public int PartCount { get; set; }
    }
}
