//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_facility_IdleHandlerWithOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblticketraiseddet
    {
        public int ticketRaisedDetId { get; set; }
        public Nullable<int> ticketId { get; set; }
        public string ticketNo { get; set; }
        public Nullable<int> operatorId { get; set; }
        public Nullable<int> supportTeamId { get; set; }
        public Nullable<int> isStatus { get; set; }
        public Nullable<System.DateTime> supportTeamAckDate { get; set; }
        public Nullable<System.DateTime> supportTeamClosureDate { get; set; }
        public Nullable<int> ifOperatorAccepts { get; set; }
        public Nullable<System.DateTime> operatorAcceptRejectDate { get; set; }
        public string commentsByOperator { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public Nullable<int> ifSupportTeamOpen { get; set; }
        public string mntAcceptReason { get; set; }
        public string mntRejectReason { get; set; }
        public string opAcceptReson { get; set; }
        public string opRejectReason { get; set; }
        public Nullable<int> machineId { get; set; }
    }
}
