//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_facility_IdleHandlerWithOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class wimerasys_employeedetails
    {
        public int id { get; set; }
        public Nullable<int> employee_code { get; set; }
        public string employee_name { get; set; }
        public string grade { get; set; }
        public Nullable<int> plant_id { get; set; }
        public string plant_name { get; set; }
        public string plant_code { get; set; }
        public Nullable<int> department_id { get; set; }
        public string department { get; set; }
        public string employee_email { get; set; }
        public string employee_number { get; set; }
        public Nullable<int> division_id { get; set; }
        public string division_name { get; set; }
    }
}
