//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_facility_IdleHandlerWithOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class wimerasys_revisiondetails
    {
        public int id { get; set; }
        public string controlPlanNumber { get; set; }
        public Nullable<int> revisionNumber { get; set; }
        public string toolLayoutNumber { get; set; }
        public Nullable<int> operationNumber { get; set; }
        public string ballunNumber { get; set; }
        public string processChar { get; set; }
        public string spclCharClass { get; set; }
        public string productChar { get; set; }
        public string dimensions { get; set; }
        public string minTolerance { get; set; }
        public string maxTolerance { get; set; }
        public string recordingMethod { get; set; }
        public string responsibility { get; set; }
        public string reactionPlan { get; set; }
        public string freqency { get; set; }
        public string time { get; set; }
        public string capacity { get; set; }
        public string evalutionMathod { get; set; }
        public string opDescription { get; set; }
        public string machines { get; set; }
        public string RCNNumber { get; set; }
        public string workInstructionNumber1 { get; set; }
        public string workInstructionNumber2 { get; set; }
        public string workInstructionNumber3 { get; set; }
        public string qaNumber1 { get; set; }
        public string qaNumber2 { get; set; }
        public string qaNumber3 { get; set; }
        public string stageDrawingNumber { get; set; }
        public string lisEvalutionMethod { get; set; }
        public string lisRecordingMethod { get; set; }
        public string lisTime { get; set; }
        public Nullable<int> lisfreqency { get; set; }
        public string settingSubGroup { get; set; }
        public string pcEvalutionMathod { get; set; }
        public string pcFreqency { get; set; }
        public Nullable<int> pcQuantity { get; set; }
    }
}
