//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_facility_IdleHandlerWithOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class wimerasys_dir
    {
        public int id { get; set; }
        public string plant { get; set; }
        public string cell { get; set; }
        public string partNumber { get; set; }
        public string partDescription { get; set; }
        public string machine { get; set; }
        public string workOrderNumber { get; set; }
        public string @operator { get; set; }
        public string cardNumber { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string shift { get; set; }
        public Nullable<int> quantity { get; set; }
        public string defectCode { get; set; }
        public string defectDescription { get; set; }
        public string scrapOrRework { get; set; }
        public string openTracker { get; set; }
        public string trackerNumber { get; set; }
        public string rootCause { get; set; }
        public string action { get; set; }
        public string responsibility { get; set; }
        public Nullable<System.DateTime> targetDate { get; set; }
        public Nullable<System.DateTime> compeletedDate { get; set; }
        public string qrCode { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
        public Nullable<int> rejectId { get; set; }
        public Nullable<int> reworkId { get; set; }
        public Nullable<int> scrapParts { get; set; }
        public Nullable<int> reworkParts { get; set; }
        public Nullable<int> okParts { get; set; }
        public string rejectOrRework { get; set; }
        public string subCell { get; set; }
        public string category { get; set; }
        public string storageLocation { get; set; }
        public Nullable<System.DateTime> checkDirQHDate { get; set; }
        public string checkDirQHVerify { get; set; }
        public string checkDirRIVerify { get; set; }
        public Nullable<System.DateTime> checkDirRIDate { get; set; }
        public string approveDirRIVerify { get; set; }
        public Nullable<System.DateTime> approveDirRIDate { get; set; }
        public string qtyHeadVerification { get; set; }
        public Nullable<System.DateTime> qtyHeadVerificationDate { get; set; }
        public string productionHeadVerification { get; set; }
        public Nullable<System.DateTime> productionHeadVerificationDate { get; set; }
        public string checkDirHODVerify { get; set; }
        public Nullable<System.DateTime> checkDirHODDate { get; set; }
        public string RIVerification { get; set; }
        public Nullable<System.DateTime> RIVerificationDate { get; set; }
    }
}
