//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDAQFanuc.ServerModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class unitworksccsEntities : DbContext
    {
        public unitworksccsEntities()
            : base("name=unitworksccsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<unitworkccs_alarm_history_master> unitworkccs_alarm_history_master { get; set; }
        public virtual DbSet<unitworkccs_configuration_tblpmchecklist> unitworkccs_configuration_tblpmchecklist { get; set; }
        public virtual DbSet<unitworkccs_configuration_tblpmcheckpoint> unitworkccs_configuration_tblpmcheckpoint { get; set; }
        public virtual DbSet<unitworkccs_configuration_tblprimitivemaintainancescheduling> unitworkccs_configuration_tblprimitivemaintainancescheduling { get; set; }
        public virtual DbSet<unitworkccs_configuration_tblsensorgroup> unitworkccs_configuration_tblsensorgroup { get; set; }
        public virtual DbSet<unitworkccs_configurationtblmachinesensor> unitworkccs_configurationtblmachinesensor { get; set; }
        public virtual DbSet<unitworkccs_configurationtblsensordatalink> unitworkccs_configurationtblsensordatalink { get; set; }
        public virtual DbSet<unitworkccs_configurationtblsensormaster> unitworkccs_configurationtblsensormaster { get; set; }
        public virtual DbSet<unitworkccs_documentuploadermaster> unitworkccs_documentuploadermaster { get; set; }
        public virtual DbSet<unitworkccs_frommail> unitworkccs_frommail { get; set; }
        public virtual DbSet<unitworkccs_handle_no_ping> unitworkccs_handle_no_ping { get; set; }
        public virtual DbSet<unitworkccs_iotgatwaypacketsdata> unitworkccs_iotgatwaypacketsdata { get; set; }
        public virtual DbSet<unitworkccs_jobcard_details> unitworkccs_jobcard_details { get; set; }
        public virtual DbSet<unitworkccs_logintrackerdetails> unitworkccs_logintrackerdetails { get; set; }
        public virtual DbSet<unitworkccs_machinedetailswimerasys> unitworkccs_machinedetailswimerasys { get; set; }
        public virtual DbSet<unitworkccs_mailmaster> unitworkccs_mailmaster { get; set; }
        public virtual DbSet<unitworkccs_message_code_master> unitworkccs_message_code_master { get; set; }
        public virtual DbSet<unitworkccs_message_history_master> unitworkccs_message_history_master { get; set; }
        public virtual DbSet<unitworkccs_monthdata> unitworkccs_monthdata { get; set; }
        public virtual DbSet<unitworkccs_operationlog> unitworkccs_operationlog { get; set; }
        public virtual DbSet<unitworkccs_parameter_sendor_data> unitworkccs_parameter_sendor_data { get; set; }
        public virtual DbSet<unitworkccs_parameter_sensor_data_current> unitworkccs_parameter_sensor_data_current { get; set; }
        public virtual DbSet<unitworkccs_parameter_sensor_data_level> unitworkccs_parameter_sensor_data_level { get; set; }
        public virtual DbSet<unitworkccs_parameter_sensor_data_pressure> unitworkccs_parameter_sensor_data_pressure { get; set; }
        public virtual DbSet<unitworkccs_parameter_sensor_data_temperature> unitworkccs_parameter_sensor_data_temperature { get; set; }
        public virtual DbSet<unitworkccs_parameters> unitworkccs_parameters { get; set; }
        public virtual DbSet<unitworkccs_pcb_details> unitworkccs_pcb_details { get; set; }
        public virtual DbSet<unitworkccs_pcb_parameters> unitworkccs_pcb_parameters { get; set; }
        public virtual DbSet<unitworkccs_pcbdaq> unitworkccs_pcbdaq { get; set; }
        public virtual DbSet<unitworkccs_pcbdaqin_tbl> unitworkccs_pcbdaqin_tbl { get; set; }
        public virtual DbSet<unitworkccs_pcbdps_master> unitworkccs_pcbdps_master { get; set; }
        public virtual DbSet<unitworkccs_pinghandler_tbl> unitworkccs_pinghandler_tbl { get; set; }
        public virtual DbSet<unitworkccs_program_execution_master> unitworkccs_program_execution_master { get; set; }
        public virtual DbSet<unitworkccs_program_master> unitworkccs_program_master { get; set; }
        public virtual DbSet<unitworkccs_sapfilegenerateddetails> unitworkccs_sapfilegenerateddetails { get; set; }
        public virtual DbSet<unitworkccs_sharathtable> unitworkccs_sharathtable { get; set; }
        public virtual DbSet<unitworkccs_shift_master> unitworkccs_shift_master { get; set; }
        public virtual DbSet<unitworkccs_smtpdetails> unitworkccs_smtpdetails { get; set; }
        public virtual DbSet<unitworkccs_tbl_autoreport_log> unitworkccs_tbl_autoreport_log { get; set; }
        public virtual DbSet<unitworkccs_tbl_autoreportbasedon> unitworkccs_tbl_autoreportbasedon { get; set; }
        public virtual DbSet<unitworkccs_tbl_autoreportsetting> unitworkccs_tbl_autoreportsetting { get; set; }
        public virtual DbSet<unitworkccs_tbl_autoreporttime> unitworkccs_tbl_autoreporttime { get; set; }
        public virtual DbSet<unitworkccs_tbl_axisdet> unitworkccs_tbl_axisdet { get; set; }
        public virtual DbSet<unitworkccs_tbl_categorynames> unitworkccs_tbl_categorynames { get; set; }
        public virtual DbSet<unitworkccs_tbl_checklistmachines> unitworkccs_tbl_checklistmachines { get; set; }
        public virtual DbSet<unitworkccs_tbl_cycletimeanalysis> unitworkccs_tbl_cycletimeanalysis { get; set; }
        public virtual DbSet<unitworkccs_tbl_deletedprogdet> unitworkccs_tbl_deletedprogdet { get; set; }
        public virtual DbSet<unitworkccs_tbl_genericfilepath> unitworkccs_tbl_genericfilepath { get; set; }
        public virtual DbSet<unitworkccs_tbl_livecbmdetails> unitworkccs_tbl_livecbmdetails { get; set; }
        public virtual DbSet<unitworkccs_tbl_livecbmparameters> unitworkccs_tbl_livecbmparameters { get; set; }
        public virtual DbSet<unitworkccs_tbl_livetblsensorvalue> unitworkccs_tbl_livetblsensorvalue { get; set; }
        public virtual DbSet<unitworkccs_tbl_machinemakedetails> unitworkccs_tbl_machinemakedetails { get; set; }
        public virtual DbSet<unitworkccs_tbl_oeedetails> unitworkccs_tbl_oeedetails { get; set; }
        public virtual DbSet<unitworkccs_tbl_oeeoperatordetails> unitworkccs_tbl_oeeoperatordetails { get; set; }
        public virtual DbSet<unitworkccs_tbl_oeereportasdivision> unitworkccs_tbl_oeereportasdivision { get; set; }
        public virtual DbSet<unitworkccs_tbl_oeeshiftdetails> unitworkccs_tbl_oeeshiftdetails { get; set; }
        public virtual DbSet<unitworkccs_tbl_pmsdashboardchecklist> unitworkccs_tbl_pmsdashboardchecklist { get; set; }
        public virtual DbSet<unitworkccs_tbl_prodandondisp> unitworkccs_tbl_prodandondisp { get; set; }
        public virtual DbSet<unitworkccs_tbl_prodmanmachine> unitworkccs_tbl_prodmanmachine { get; set; }
        public virtual DbSet<unitworkccs_tbl_prodorderlosses> unitworkccs_tbl_prodorderlosses { get; set; }
        public virtual DbSet<unitworkccs_tbl_reportmaster> unitworkccs_tbl_reportmaster { get; set; }
        public virtual DbSet<unitworkccs_tbl_savencprogver> unitworkccs_tbl_savencprogver { get; set; }
        public virtual DbSet<unitworkccs_tbl_screenpagesdetails> unitworkccs_tbl_screenpagesdetails { get; set; }
        public virtual DbSet<unitworkccs_tbl_servodetails> unitworkccs_tbl_servodetails { get; set; }
        public virtual DbSet<unitworkccs_tbl_utilreport> unitworkccs_tbl_utilreport { get; set; }
        public virtual DbSet<unitworkccs_tblactivitylog> unitworkccs_tblactivitylog { get; set; }
        public virtual DbSet<unitworkccs_tblandondispdet> unitworkccs_tblandondispdet { get; set; }
        public virtual DbSet<unitworkccs_tblandondisplayrotate> unitworkccs_tblandondisplayrotate { get; set; }
        public virtual DbSet<unitworkccs_tblandonimagetextscheduleddisplay> unitworkccs_tblandonimagetextscheduleddisplay { get; set; }
        public virtual DbSet<unitworkccs_tblapp_paths> unitworkccs_tblapp_paths { get; set; }
        public virtual DbSet<unitworkccs_tblatccounter> unitworkccs_tblatccounter { get; set; }
        public virtual DbSet<unitworkccs_tblbookstock> unitworkccs_tblbookstock { get; set; }
        public virtual DbSet<unitworkccs_tblbottelneck> unitworkccs_tblbottelneck { get; set; }
        public virtual DbSet<unitworkccs_tblbreakdown> unitworkccs_tblbreakdown { get; set; }
        public virtual DbSet<unitworkccs_tblbreakdown_reportdetails> unitworkccs_tblbreakdown_reportdetails { get; set; }
        public virtual DbSet<unitworkccs_tblbreakdowncodes> unitworkccs_tblbreakdowncodes { get; set; }
        public virtual DbSet<unitworkccs_tblbreakdowntickect> unitworkccs_tblbreakdowntickect { get; set; }
        public virtual DbSet<unitworkccs_tblbusinessdetails> unitworkccs_tblbusinessdetails { get; set; }
        public virtual DbSet<unitworkccs_tblcategory> unitworkccs_tblcategory { get; set; }
        public virtual DbSet<unitworkccs_tblcategorydetails> unitworkccs_tblcategorydetails { get; set; }
        public virtual DbSet<unitworkccs_tblcategorymaster> unitworkccs_tblcategorymaster { get; set; }
        public virtual DbSet<unitworkccs_tblcell> unitworkccs_tblcell { get; set; }
        public virtual DbSet<unitworkccs_tblcellfinalmaster> unitworkccs_tblcellfinalmaster { get; set; }
        public virtual DbSet<unitworkccs_tblcellpart> unitworkccs_tblcellpart { get; set; }
        public virtual DbSet<unitworkccs_tblchecklist_details> unitworkccs_tblchecklist_details { get; set; }
        public virtual DbSet<unitworkccs_tblchecklist_header> unitworkccs_tblchecklist_header { get; set; }
        public virtual DbSet<unitworkccs_tblchildfgpartno> unitworkccs_tblchildfgpartno { get; set; }
        public virtual DbSet<unitworkccs_tblclassmaster> unitworkccs_tblclassmaster { get; set; }
        public virtual DbSet<unitworkccs_tblcontrolplan> unitworkccs_tblcontrolplan { get; set; }
        public virtual DbSet<unitworkccs_tblcontrolplandetails> unitworkccs_tblcontrolplandetails { get; set; }
        public virtual DbSet<unitworkccs_tblcustomer> unitworkccs_tblcustomer { get; set; }
        public virtual DbSet<unitworkccs_tbldailyprodstatus> unitworkccs_tbldailyprodstatus { get; set; }
        public virtual DbSet<unitworkccs_tbldaytiming> unitworkccs_tbldaytiming { get; set; }
        public virtual DbSet<unitworkccs_tbldefectcodemaster> unitworkccs_tbldefectcodemaster { get; set; }
        public virtual DbSet<unitworkccs_tbldepartmentdetails> unitworkccs_tbldepartmentdetails { get; set; }
        public virtual DbSet<unitworkccs_tbldirlineinspector> unitworkccs_tbldirlineinspector { get; set; }
        public virtual DbSet<unitworkccs_tbldirqualityhead> unitworkccs_tbldirqualityhead { get; set; }
        public virtual DbSet<unitworkccs_tbldowntimecategory> unitworkccs_tbldowntimecategory { get; set; }
        public virtual DbSet<unitworkccs_tbldowntimedetails> unitworkccs_tbldowntimedetails { get; set; }
        public virtual DbSet<unitworkccs_tbldryrun> unitworkccs_tbldryrun { get; set; }
        public virtual DbSet<unitworkccs_tblemailescalation> unitworkccs_tblemailescalation { get; set; }
        public virtual DbSet<unitworkccs_tblemployeeshiftdetails> unitworkccs_tblemployeeshiftdetails { get; set; }
        public virtual DbSet<unitworkccs_tblendcodes> unitworkccs_tblendcodes { get; set; }
        public virtual DbSet<unitworkccs_tblescalationlog> unitworkccs_tblescalationlog { get; set; }
        public virtual DbSet<unitworkccs_tblescalationmatrix> unitworkccs_tblescalationmatrix { get; set; }
        public virtual DbSet<unitworkccs_tblescalationprioritydetails> unitworkccs_tblescalationprioritydetails { get; set; }
        public virtual DbSet<unitworkccs_tblescalationtiming> unitworkccs_tblescalationtiming { get; set; }
        public virtual DbSet<unitworkccs_tblfgandcellallocation> unitworkccs_tblfgandcellallocation { get; set; }
        public virtual DbSet<unitworkccs_tblfgpartnodet> unitworkccs_tblfgpartnodet { get; set; }
        public virtual DbSet<unitworkccs_tblgeneraldefectcodes> unitworkccs_tblgeneraldefectcodes { get; set; }
        public virtual DbSet<unitworkccs_tblgenericworkcodes> unitworkccs_tblgenericworkcodes { get; set; }
        public virtual DbSet<unitworkccs_tblgenericworkentry> unitworkccs_tblgenericworkentry { get; set; }
        public virtual DbSet<unitworkccs_tblhistpms> unitworkccs_tblhistpms { get; set; }
        public virtual DbSet<unitworkccs_tblholdcodes> unitworkccs_tblholdcodes { get; set; }
        public virtual DbSet<unitworkccs_tblholidaymanagment> unitworkccs_tblholidaymanagment { get; set; }
        public virtual DbSet<unitworkccs_tblholidays> unitworkccs_tblholidays { get; set; }
        public virtual DbSet<unitworkccs_tblholidaytypemasters> unitworkccs_tblholidaytypemasters { get; set; }
        public virtual DbSet<unitworkccs_tblipaddress> unitworkccs_tblipaddress { get; set; }
        public virtual DbSet<unitworkccs_tblissuedreceived> unitworkccs_tblissuedreceived { get; set; }
        public virtual DbSet<unitworkccs_tbllivedailyprodstatus> unitworkccs_tbllivedailyprodstatus { get; set; }
        public virtual DbSet<unitworkccs_tbllivemode> unitworkccs_tbllivemode { get; set; }
        public virtual DbSet<unitworkccs_tbllossescodes> unitworkccs_tbllossescodes { get; set; }
        public virtual DbSet<unitworkccs_tbllossofentry> unitworkccs_tbllossofentry { get; set; }
        public virtual DbSet<unitworkccs_tblmachineaxisdetails> unitworkccs_tblmachineaxisdetails { get; set; }
        public virtual DbSet<unitworkccs_tblmachinecategory> unitworkccs_tblmachinecategory { get; set; }
        public virtual DbSet<unitworkccs_tblmachinecategorynames> unitworkccs_tblmachinecategorynames { get; set; }
        public virtual DbSet<unitworkccs_tblmachinedetails> unitworkccs_tblmachinedetails { get; set; }
        public virtual DbSet<unitworkccs_tblmailids> unitworkccs_tblmailids { get; set; }
        public virtual DbSet<unitworkccs_tblmasterparts_st_sw> unitworkccs_tblmasterparts_st_sw { get; set; }
        public virtual DbSet<unitworkccs_tblmastervalue> unitworkccs_tblmastervalue { get; set; }
        public virtual DbSet<unitworkccs_tblmaterialmaster> unitworkccs_tblmaterialmaster { get; set; }
        public virtual DbSet<unitworkccs_tblmimics> unitworkccs_tblmimics { get; set; }
        public virtual DbSet<unitworkccs_tblmode> unitworkccs_tblmode { get; set; }
        public virtual DbSet<unitworkccs_tblmodetemp> unitworkccs_tblmodetemp { get; set; }
        public virtual DbSet<unitworkccs_tblmodulehelper> unitworkccs_tblmodulehelper { get; set; }
        public virtual DbSet<unitworkccs_tblmodulemaster> unitworkccs_tblmodulemaster { get; set; }
        public virtual DbSet<unitworkccs_tblmodules> unitworkccs_tblmodules { get; set; }
        public virtual DbSet<unitworkccs_tblmultipleworkorder> unitworkccs_tblmultipleworkorder { get; set; }
        public virtual DbSet<unitworkccs_tblncprogramtransfermain> unitworkccs_tblncprogramtransfermain { get; set; }
        public virtual DbSet<unitworkccs_tblnoofaxis> unitworkccs_tblnoofaxis { get; set; }
        public virtual DbSet<unitworkccs_tbloeedashboardfinalvariables> unitworkccs_tbloeedashboardfinalvariables { get; set; }
        public virtual DbSet<unitworkccs_tbloeedashboardvariables> unitworkccs_tbloeedashboardvariables { get; set; }
        public virtual DbSet<unitworkccs_tbloeedashboardvariablestoday> unitworkccs_tbloeedashboardvariablestoday { get; set; }
        public virtual DbSet<unitworkccs_tbloperatordashboard> unitworkccs_tbloperatordashboard { get; set; }
        public virtual DbSet<unitworkccs_tbloperatordetails> unitworkccs_tbloperatordetails { get; set; }
        public virtual DbSet<unitworkccs_tbloperatorheader> unitworkccs_tbloperatorheader { get; set; }
        public virtual DbSet<unitworkccs_tbloperatorlogindetails> unitworkccs_tbloperatorlogindetails { get; set; }
        public virtual DbSet<unitworkccs_tbloperatormachinedetails> unitworkccs_tbloperatormachinedetails { get; set; }
        public virtual DbSet<unitworkccs_tblpallet> unitworkccs_tblpallet { get; set; }
        public virtual DbSet<unitworkccs_tblpartlearningreport> unitworkccs_tblpartlearningreport { get; set; }
        public virtual DbSet<unitworkccs_tblparts> unitworkccs_tblparts { get; set; }
        public virtual DbSet<unitworkccs_tblpartscountandcutting> unitworkccs_tblpartscountandcutting { get; set; }
        public virtual DbSet<unitworkccs_tblpir> unitworkccs_tblpir { get; set; }
        public virtual DbSet<unitworkccs_tblpirminmax> unitworkccs_tblpirminmax { get; set; }
        public virtual DbSet<unitworkccs_tblplanlinkagemaster> unitworkccs_tblplanlinkagemaster { get; set; }
        public virtual DbSet<unitworkccs_tblplannedbreak> unitworkccs_tblplannedbreak { get; set; }
        public virtual DbSet<unitworkccs_tblplant> unitworkccs_tblplant { get; set; }
        public virtual DbSet<unitworkccs_tblpmsdetails> unitworkccs_tblpmsdetails { get; set; }
        public virtual DbSet<unitworkccs_tblprecentcolour> unitworkccs_tblprecentcolour { get; set; }
        public virtual DbSet<unitworkccs_tblpresenttool> unitworkccs_tblpresenttool { get; set; }
        public virtual DbSet<unitworkccs_tblpriorityalarms> unitworkccs_tblpriorityalarms { get; set; }
        public virtual DbSet<unitworkccs_tblprocess> unitworkccs_tblprocess { get; set; }
        public virtual DbSet<unitworkccs_tblprodplanmasters> unitworkccs_tblprodplanmasters { get; set; }
        public virtual DbSet<unitworkccs_tblproduct> unitworkccs_tblproduct { get; set; }
        public virtual DbSet<unitworkccs_tblproductwisedefectcodes> unitworkccs_tblproductwisedefectcodes { get; set; }
        public virtual DbSet<unitworkccs_tblprogramtransferhistory> unitworkccs_tblprogramtransferhistory { get; set; }
        public virtual DbSet<unitworkccs_tblraisedticket> unitworkccs_tblraisedticket { get; set; }
        public virtual DbSet<unitworkccs_tblrejectiondetails> unitworkccs_tblrejectiondetails { get; set; }
        public virtual DbSet<unitworkccs_tblrejectqty> unitworkccs_tblrejectqty { get; set; }
        public virtual DbSet<unitworkccs_tblrejectreason> unitworkccs_tblrejectreason { get; set; }
        public virtual DbSet<unitworkccs_tblreportholder> unitworkccs_tblreportholder { get; set; }
        public virtual DbSet<unitworkccs_tblreworkdetails> unitworkccs_tblreworkdetails { get; set; }
        public virtual DbSet<unitworkccs_tblreworkreasons> unitworkccs_tblreworkreasons { get; set; }
        public virtual DbSet<unitworkccs_tblrolemodulelink> unitworkccs_tblrolemodulelink { get; set; }
        public virtual DbSet<unitworkccs_tblroles> unitworkccs_tblroles { get; set; }
        public virtual DbSet<unitworkccs_tblroutingno> unitworkccs_tblroutingno { get; set; }
        public virtual DbSet<unitworkccs_tblsapinput> unitworkccs_tblsapinput { get; set; }
        public virtual DbSet<unitworkccs_tblsar> unitworkccs_tblsar { get; set; }
        public virtual DbSet<unitworkccs_tblsarminmax> unitworkccs_tblsarminmax { get; set; }
        public virtual DbSet<unitworkccs_tblsendermailid> unitworkccs_tblsendermailid { get; set; }
        public virtual DbSet<unitworkccs_tblsetupmaint> unitworkccs_tblsetupmaint { get; set; }
        public virtual DbSet<unitworkccs_tblshift_breaks> unitworkccs_tblshift_breaks { get; set; }
        public virtual DbSet<unitworkccs_tblshift_mstr> unitworkccs_tblshift_mstr { get; set; }
        public virtual DbSet<unitworkccs_tblshiftdetails> unitworkccs_tblshiftdetails { get; set; }
        public virtual DbSet<unitworkccs_tblshiftdetails_machinewise> unitworkccs_tblshiftdetails_machinewise { get; set; }
        public virtual DbSet<unitworkccs_tblshiftmethod> unitworkccs_tblshiftmethod { get; set; }
        public virtual DbSet<unitworkccs_tblshiftplanner> unitworkccs_tblshiftplanner { get; set; }
        public virtual DbSet<unitworkccs_tblshop> unitworkccs_tblshop { get; set; }
        public virtual DbSet<unitworkccs_tblsmsdetails> unitworkccs_tblsmsdetails { get; set; }
        public virtual DbSet<unitworkccs_tblsourcemaster> unitworkccs_tblsourcemaster { get; set; }
        public virtual DbSet<unitworkccs_tblstatusmaster> unitworkccs_tblstatusmaster { get; set; }
        public virtual DbSet<unitworkccs_tblstdtoollife> unitworkccs_tblstdtoollife { get; set; }
        public virtual DbSet<unitworkccs_tblstoppage> unitworkccs_tblstoppage { get; set; }
        public virtual DbSet<unitworkccs_tblsubcellfinalmaster> unitworkccs_tblsubcellfinalmaster { get; set; }
        public virtual DbSet<unitworkccs_tblsystemconfig> unitworkccs_tblsystemconfig { get; set; }
        public virtual DbSet<unitworkccs_tbltallstockavailibility> unitworkccs_tbltallstockavailibility { get; set; }
        public virtual DbSet<unitworkccs_tblticketraiseddet> unitworkccs_tblticketraiseddet { get; set; }
        public virtual DbSet<unitworkccs_tblticketreason> unitworkccs_tblticketreason { get; set; }
        public virtual DbSet<unitworkccs_tbltoolandsocketdetails> unitworkccs_tbltoolandsocketdetails { get; set; }
        public virtual DbSet<unitworkccs_tbltoolbrdnreasonlvl1> unitworkccs_tbltoolbrdnreasonlvl1 { get; set; }
        public virtual DbSet<unitworkccs_tbltoolbrkdnreason> unitworkccs_tbltoolbrkdnreason { get; set; }
        public virtual DbSet<unitworkccs_tbltoolcounter> unitworkccs_tbltoolcounter { get; set; }
        public virtual DbSet<unitworkccs_tbltoollifeoperator> unitworkccs_tbltoollifeoperator { get; set; }
        public virtual DbSet<unitworkccs_tbltools> unitworkccs_tbltools { get; set; }
        public virtual DbSet<unitworkccs_tbltosapfilepath> unitworkccs_tbltosapfilepath { get; set; }
        public virtual DbSet<unitworkccs_tbltosapshopnames> unitworkccs_tbltosapshopnames { get; set; }
        public virtual DbSet<unitworkccs_tbltrialpartcount> unitworkccs_tbltrialpartcount { get; set; }
        public virtual DbSet<unitworkccs_tblunit> unitworkccs_tblunit { get; set; }
        public virtual DbSet<unitworkccs_tblusers> unitworkccs_tblusers { get; set; }
        public virtual DbSet<unitworkccs_tblwolossess> unitworkccs_tblwolossess { get; set; }
        public virtual DbSet<unitworkccs_tblworeport> unitworkccs_tblworeport { get; set; }
        public virtual DbSet<unitworkccs_tblworkcenter> unitworkccs_tblworkcenter { get; set; }
        public virtual DbSet<unitworkccs_tblworkorderentry> unitworkccs_tblworkorderentry { get; set; }
        public virtual DbSet<unitworkccs_weekdata> unitworkccs_weekdata { get; set; }
        public virtual DbSet<wimerasys_controlplan> wimerasys_controlplan { get; set; }
        public virtual DbSet<wimerasys_cpdetails> wimerasys_cpdetails { get; set; }
        public virtual DbSet<wimerasys_dir> wimerasys_dir { get; set; }
        public virtual DbSet<wimerasys_documents> wimerasys_documents { get; set; }
        public virtual DbSet<wimerasys_employeedetails> wimerasys_employeedetails { get; set; }
        public virtual DbSet<wimerasys_evaluation> wimerasys_evaluation { get; set; }
        public virtual DbSet<wimerasys_fgandcellallocationdetails> wimerasys_fgandcellallocationdetails { get; set; }
        public virtual DbSet<wimerasys_process> wimerasys_process { get; set; }
        public virtual DbSet<wimerasys_product> wimerasys_product { get; set; }
        public virtual DbSet<wimerasys_productwisedefectdetails> wimerasys_productwisedefectdetails { get; set; }
        public virtual DbSet<wimerasys_revisiondetails> wimerasys_revisiondetails { get; set; }
        public virtual DbSet<wimerasys_scc> wimerasys_scc { get; set; }
        public virtual DbSet<unitworkccs_parameter_tool_data> unitworkccs_parameter_tool_data { get; set; }
        public virtual DbSet<unitworkccs_parameters_master> unitworkccs_parameters_master { get; set; }
        public virtual DbSet<unitworkccs_tbl_axisdetails1> unitworkccs_tbl_axisdetails1 { get; set; }
        public virtual DbSet<unitworkccs_tbl_axisdetails2> unitworkccs_tbl_axisdetails2 { get; set; }
    }
}
