//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDAQFanuc.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tbltools
    {
        public int toolId { get; set; }
        public string toolName { get; set; }
        public string toolLocation { get; set; }
        public string toolDesc { get; set; }
        public string toolBatchNo { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> plantId { get; set; }
        public string sapCode { get; set; }
        public string grnNo { get; set; }
        public string inspLotNo { get; set; }
        public Nullable<int> slipNo { get; set; }
        public string plantCode { get; set; }
        public string toolSapCode { get; set; }
        public string UOM { get; set; }
        public string toolType { get; set; }
        public string toolInsert { get; set; }
    }
}
