//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDAQFanuc.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tbldirlineinspector
    {
        public int dirLineInspId { get; set; }
        public Nullable<int> plantId { get; set; }
        public Nullable<int> cellId { get; set; }
        public Nullable<int> subCellId { get; set; }
        public Nullable<int> machineId { get; set; }
        public string partNumber { get; set; }
        public string partDescription { get; set; }
        public string workorderNumber { get; set; }
        public Nullable<int> operatorId { get; set; }
        public string employeeNo { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> quantity { get; set; }
        public string defectCode { get; set; }
        public string defectDescription { get; set; }
        public string partQrCode { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public string shift { get; set; }
    }
}
