//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDAQFanuc.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tbllossescodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public unitworkccs_tbllossescodes()
        {
            this.unitworkccs_tblemailescalation = new HashSet<unitworkccs_tblemailescalation>();
            this.unitworkccs_tblemailescalation1 = new HashSet<unitworkccs_tblemailescalation>();
            this.unitworkccs_tblemailescalation2 = new HashSet<unitworkccs_tblemailescalation>();
            this.unitworkccs_tblescalationlog = new HashSet<unitworkccs_tblescalationlog>();
            this.unitworkccs_tbllivemode = new HashSet<unitworkccs_tbllivemode>();
            this.unitworkccs_tblmode = new HashSet<unitworkccs_tblmode>();
            this.unitworkccs_tblmodetemp = new HashSet<unitworkccs_tblmodetemp>();
            this.unitworkccs_tblsetupmaint = new HashSet<unitworkccs_tblsetupmaint>();
            this.unitworkccs_tblmode1 = new HashSet<unitworkccs_tblmode>();
            this.unitworkccs_tbllossofentry = new HashSet<unitworkccs_tbllossofentry>();
        }
    
        public int LossCodeID { get; set; }
        public string LossCode { get; set; }
        public string LossCodeDesc { get; set; }
        public string MessageType { get; set; }
        public int LossCodesLevel { get; set; }
        public Nullable<int> LossCodesLevel1ID { get; set; }
        public Nullable<int> LossCodesLevel2ID { get; set; }
        public string ContributeTo { get; set; }
        public int IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> EndCode { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int ServerTabCheck { get; set; }
        public int ServerTabFlagSync { get; set; }
        public decimal TargetPercent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tblemailescalation> unitworkccs_tblemailescalation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tblemailescalation> unitworkccs_tblemailescalation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tblemailescalation> unitworkccs_tblemailescalation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tblescalationlog> unitworkccs_tblescalationlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tbllivemode> unitworkccs_tbllivemode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tblmode> unitworkccs_tblmode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tblmodetemp> unitworkccs_tblmodetemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tblsetupmaint> unitworkccs_tblsetupmaint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tblmode> unitworkccs_tblmode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tbllossofentry> unitworkccs_tbllossofentry { get; set; }
    }
}
