//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDAQFanuc.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblplanlinkagemaster
    {
        public int planLinkageId { get; set; }
        public Nullable<int> plantId { get; set; }
        public Nullable<int> scheduleId { get; set; }
        public Nullable<System.DateTime> scheduleDate { get; set; }
        public Nullable<int> shiftId { get; set; }
        public string productionOrder { get; set; }
        public string routingId { get; set; }
        public Nullable<int> operation { get; set; }
        public Nullable<decimal> workOrderQty { get; set; }
        public Nullable<int> workOrderCompletedQty { get; set; }
        public string resourceId { get; set; }
        public Nullable<int> scheduledQty { get; set; }
        public Nullable<System.DateTime> plannedStartTime { get; set; }
        public Nullable<System.DateTime> plannedEndTime { get; set; }
        public Nullable<decimal> setUpTime { get; set; }
        public Nullable<System.DateTime> sapDateTimeStamp { get; set; }
        public string fgPartNo { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public string lastUpdatedUse { get; set; }
        public Nullable<int> numUpdates { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public string partName { get; set; }
        public Nullable<decimal> idealCycleTime { get; set; }
        public Nullable<int> targetPerHr { get; set; }
        public string unit { get; set; }
    }
}
