//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDAQFanuc.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblpirminmax
    {
        public int pmid { get; set; }
        public Nullable<decimal> pirmin { get; set; }
        public Nullable<decimal> pirmax { get; set; }
        public string pirstatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public int Isdeleted { get; set; }
        public Nullable<int> pid { get; set; }
    }
}
