//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDAQFanuc.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_parameter_tool_data
    {
        public int parameterToolDataId { get; set; }
        public Nullable<int> machineId { get; set; }
        public Nullable<System.DateTime> parameterToolDataCapturedDate { get; set; }
        public string toolGroupName { get; set; }
        public string toolNumber { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> partsproduced { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<sbyte> isDeleted { get; set; }
        public Nullable<System.DateTime> correctedDate { get; set; }
    }
}
