//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDAQFanuc.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblpir
    {
        public int pid { get; set; }
        public string opNo { get; set; }
        public string ballunNo { get; set; }
        public string partNo { get; set; }
        public string specification { get; set; }
        public string prodAndLocation { get; set; }
        public string specialChar { get; set; }
        public string freq { get; set; }
        public Nullable<int> prodQuality { get; set; }
        public Nullable<int> rejarctionQuality { get; set; }
        public Nullable<int> machineId { get; set; }
        public string shift { get; set; }
        public string responsibility { get; set; }
        public int createdBy { get; set; }
        public System.DateTime createdOn { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public int isDeleted { get; set; }
    }
}
