//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDAQFanuc.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_configuration_tblprimitivemaintainancescheduling
    {
        public int pmid { get; set; }
        public int MachineID { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string CellName { get; set; }
        public int CellID { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public string plantName { get; set; }
        public string shopname { get; set; }
        public int MonthID { get; set; }
        public int WeekID { get; set; }
    
        public virtual unitworkccs_tblcell unitworkccs_tblcell { get; set; }
        public virtual unitworkccs_tblmachinedetails unitworkccs_tblmachinedetails { get; set; }
        public virtual unitworkccs_tblplant unitworkccs_tblplant { get; set; }
        public virtual unitworkccs_tblshop unitworkccs_tblshop { get; set; }
    }
}
