//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDAQFanuc.ServerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wimerasys_controlplan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wimerasys_controlplan()
        {
            this.wimerasys_cpdetails = new HashSet<wimerasys_cpdetails>();
        }
    
        public int id { get; set; }
        public string cell { get; set; }
        public string subCell { get; set; }
        public string fgNumber { get; set; }
        public string fgDescription { get; set; }
        public string childPartNumber { get; set; }
        public string routingNumber { get; set; }
        public string controlPlanNumber { get; set; }
        public Nullable<int> revisionNumber { get; set; }
        public Nullable<System.DateTime> revisionDate { get; set; }
        public string plant { get; set; }
        public string controlPlanType { get; set; }
        public string customerRefNumber { get; set; }
        public string mppPartNumber { get; set; }
        public string customerRevNumber { get; set; }
        public string keyContactDetails { get; set; }
        public string coreTeam { get; set; }
        public string supplierCode { get; set; }
        public Nullable<System.DateTime> customerApprovalDate { get; set; }
        public string preparedBy { get; set; }
        public Nullable<int> firstCheck { get; set; }
        public string firstCheckedBy { get; set; }
        public Nullable<int> secondCheck { get; set; }
        public string secondCheckedBy { get; set; }
        public Nullable<int> thirdCheck { get; set; }
        public string thirdCheckedBy { get; set; }
        public Nullable<int> approved { get; set; }
        public string approvedBy { get; set; }
        public Nullable<System.DateTime> firstCheckedDate { get; set; }
        public Nullable<System.DateTime> secondCheckedDate { get; set; }
        public Nullable<System.DateTime> thirdCheckedDate { get; set; }
        public Nullable<System.DateTime> preparedDate { get; set; }
        public Nullable<System.DateTime> approvedDate { get; set; }
        public Nullable<int> postToCheck { get; set; }
        public Nullable<int> frequency { get; set; }
        public Nullable<int> days { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wimerasys_cpdetails> wimerasys_cpdetails { get; set; }
    }
}
