//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Status_UAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_documentuploadermaster
    {
        public int DocumnetUploaderId { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> Did { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int Isdeleted { get; set; }
        public int isactive { get; set; }
        public string DocumnetUploaderFor { get; set; }
        public string PictureName { get; set; }
        public string PicturePath { get; set; }
    }
}
