//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Status_UAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblescalationmatrix
    {
        public long escalationId { get; set; }
        public Nullable<int> employeeId { get; set; }
        public string employeeName { get; set; }
        public Nullable<int> opNo { get; set; }
        public string contactNo { get; set; }
        public string cell { get; set; }
        public string cellId { get; set; }
        public string subCell { get; set; }
        public string subCellId { get; set; }
        public string role { get; set; }
        public Nullable<int> roleId { get; set; }
        public string categoryId { get; set; }
        public string category { get; set; }
        public string shift { get; set; }
        public Nullable<int> shiftId { get; set; }
        public Nullable<int> machineId { get; set; }
        public string machineName { get; set; }
        public string smsPriority { get; set; }
        public Nullable<int> timeToBeTriggered { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<int> plantId { get; set; }
        public string plantCode { get; set; }
    }
}
