//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Status_UAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblchecklist_details
    {
        public int checkListId { get; set; }
        public Nullable<int> HeaderId { get; set; }
        public string WhatToCheck { get; set; }
        public string How { get; set; }
        public string Frequency { get; set; }
        public string RunningHrs { get; set; }
        public Nullable<int> PartsCount { get; set; }
        public string PeriodFrequency { get; set; }
        public string Date { get; set; }
        public string IsOk { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> IsPrepared { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public string comment { get; set; }
        public Nullable<bool> IsNumeric { get; set; }
        public Nullable<bool> IsText { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<int> NumericValue { get; set; }
        public string TextValue { get; set; }
        public Nullable<int> IsDashBoardEntry { get; set; }
    }
}
