//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Status_UAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblfgpartnodet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public unitworkccs_tblfgpartnodet()
        {
            this.unitworkccs_tbl_prodmanmachine = new HashSet<unitworkccs_tbl_prodmanmachine>();
        }
    
        public int fgPartId { get; set; }
        public Nullable<int> partId { get; set; }
        public string partCountMethod { get; set; }
        public Nullable<int> operationNo { get; set; }
        public string workOrderNo { get; set; }
        public string noOfPartsPerCycle { get; set; }
        public Nullable<int> isClosed { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> closedDate { get; set; }
        public Nullable<int> operatorId { get; set; }
        public Nullable<int> machineId { get; set; }
        public string correctedDate { get; set; }
        public string shift { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<int> planLinkageId { get; set; }
        public Nullable<int> actaulValue { get; set; }
        public Nullable<int> targetQty { get; set; }
        public Nullable<double> availibility { get; set; }
        public Nullable<double> performance { get; set; }
        public Nullable<double> quality { get; set; }
        public Nullable<double> oee { get; set; }
        public string fgPartNo { get; set; }
        public Nullable<decimal> idealCycleTime { get; set; }
        public string unit { get; set; }
        public Nullable<int> scheduledQty { get; set; }
        public Nullable<System.DateTime> plannedStartTime { get; set; }
        public Nullable<System.DateTime> plannedEndTime { get; set; }
        public string routingId { get; set; }
        public string partName { get; set; }
        public Nullable<int> workOrderCompletedQty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<unitworkccs_tbl_prodmanmachine> unitworkccs_tbl_prodmanmachine { get; set; }
    }
}
