//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Status_UAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblsmsdetails
    {
        public int smsId { get; set; }
        public Nullable<int> machineId { get; set; }
        public string contactNo { get; set; }
        public Nullable<int> ticketId { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public string responseId { get; set; }
        public string idleResponseId { get; set; }
        public Nullable<int> idleSms { get; set; }
        public string shift { get; set; }
        public string message { get; set; }
        public string correctedDate { get; set; }
        public string cellId { get; set; }
        public string subCellId { get; set; }
        public string categoryId { get; set; }
        public string smsPriority { get; set; }
        public Nullable<int> timeToBeTriggered { get; set; }
        public string employeeName { get; set; }
        public Nullable<int> opNo { get; set; }
    }
}
