//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Status_UAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tblmastervalue
    {
        public long masterValueId { get; set; }
        public string masterValueName { get; set; }
        public string masterValueDesc { get; set; }
        public Nullable<decimal> masterValue { get; set; }
    }
}
