//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Status_UAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_tbltrialpartcount
    {
        public int trialPartId { get; set; }
        public Nullable<int> trialPartCount { get; set; }
        public Nullable<int> machineId { get; set; }
        public string correctedDate { get; set; }
        public string shift { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> ticketOpenDate { get; set; }
        public Nullable<System.DateTime> ticketCloseDate { get; set; }
        public Nullable<int> ticketId { get; set; }
    }
}
