//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Status_UAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_program_execution_master
    {
        public int programExecutionId { get; set; }
        public string programName { get; set; }
        public Nullable<int> machineId { get; set; }
        public Nullable<System.DateTime> programExcutedDateTime { get; set; }
        public Nullable<System.DateTime> programStartDateTime { get; set; }
        public Nullable<System.DateTime> programEndDateTime { get; set; }
        public Nullable<System.DateTime> correctedDate { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
    }
}
