//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_Status_UAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitworkccs_machinedetailswimerasys
    {
        public int machineId { get; set; }
        public string machineName { get; set; }
        public Nullable<int> transmissionFrequency { get; set; }
        public string loggerType { get; set; }
        public string machineIp { get; set; }
        public Nullable<int> machinePort { get; set; }
        public Nullable<int> numOfAxis { get; set; }
        public Nullable<int> toolGroupNum { get; set; }
        public Nullable<int> numberOfCurrent { get; set; }
        public Nullable<int> numberOfTemperature { get; set; }
        public Nullable<int> numberOfPresure { get; set; }
        public Nullable<int> numberOfLevel { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
    }
}
